import React from 'react';
import type { Trip } from '../types';
import { TicketIcon, BedIcon, WalletIcon } from './icons';

interface WalletProps {
    trip: Trip;
}

const Wallet: React.FC<WalletProps> = ({ trip }) => {
    if (!trip.bookings) {
        return (
            <div className="bg-black/20 backdrop-blur-xl border border-white/10 rounded-3xl p-6 text-center">
                 <h2 className="text-2xl font-bold text-primary mb-4">Wallet & Docs</h2>
                 <p className="animate-pulse text-gray-400">Booking details are being generated by AI. This may take a moment...</p>
            </div>
        )
    }

    const { flight, hotel, receipt } = trip.bookings;

    return (
        <div className="space-y-6">
            <h2 className="text-3xl font-bold text-white mb-4">Wallet & Docs</h2>
            
            <div className="bg-black/20 backdrop-blur-xl border border-white/10 rounded-3xl p-4 sm:p-6">
                <h3 className="font-bold flex items-center mb-2 text-white"><TicketIcon className="w-5 h-5 mr-2"/>Flight E-Ticket</h3>
                <div className="bg-white/5 p-4 rounded-xl space-y-2">
                    <div className="flex justify-between items-center">
                        <span className="text-sm text-gray-400">{flight.airline} {flight.flightNumber}</span>
                        <span className="font-mono text-xs bg-green-500/20 text-green-300 px-2 py-1 rounded">CONFIRMED</span>
                    </div>
                    <div className="flex justify-between items-end">
                        <div>
                            <p className="text-2xl font-bold text-white">{flight.from}</p>
                            <p className="text-sm text-gray-300">{flight.departure}</p>
                        </div>
                        <div className="flex-1 text-center text-primary">---✈---</div>
                         <div>
                            <p className="text-2xl font-bold text-right text-white">{flight.to}</p>
                            <p className="text-sm text-right text-gray-300">{flight.arrival}</p>
                        </div>
                    </div>
                </div>
            </div>

            <div className="bg-black/20 backdrop-blur-xl border border-white/10 rounded-3xl p-4 sm:p-6">
                 <h3 className="font-bold flex items-center mb-2 text-white"><BedIcon className="w-5 h-5 mr-2"/>Hotel Voucher</h3>
                 <div className="bg-white/5 p-4 rounded-xl">
                     <h4 className="font-semibold text-white">{hotel.name}</h4>
                     <p className="text-sm text-gray-400">{hotel.address}</p>
                     <div className="mt-2 flex justify-between text-xs border-t border-white/10 pt-2 text-gray-300">
                        <span>Check-in: {hotel.checkIn}</span>
                        <span>Check-out: {hotel.checkOut}</span>
                     </div>
                 </div>
            </div>

            <div className="bg-black/20 backdrop-blur-xl border border-white/10 rounded-3xl p-4 sm:p-6">
                 <h3 className="font-bold flex items-center mb-2 text-white"><WalletIcon className="w-5 h-5 mr-2"/>Payment Receipt</h3>
                 <div className="bg-white/5 p-4 rounded-xl text-sm text-gray-300">
                    <div className="flex justify-between mb-2">
                        <span>Receipt ID: {receipt.id}</span>
                        <span>Date: {receipt.date}</span>
                    </div>
                    <ul className="border-y border-white/10 py-2 space-y-1">
                        {receipt.items.map((item, i) => (
                             <li key={i} className="flex justify-between">
                                <span>{item.description}</span>
                                <span>₹{item.amount.toLocaleString()}</span>
                            </li>
                        ))}
                    </ul>
                     <div className="flex justify-between font-bold pt-2 text-white">
                        <span>Total Paid</span>
                        <span>₹{receipt.items.reduce((sum, i) => sum + i.amount, 0).toLocaleString()}</span>
                    </div>
                 </div>
            </div>
        </div>
    );
};

export default Wallet;
